### ISSUE TITLE
看板任务-自动接任务问题

### ISSUE THREAD

**Issue by shermanheng4862** [cwsam66/mobileanjian#1]
使用版本：激情ROX-辅助-20210817.apk
功能设置：看板任务，自动接任务
问题1：第二行第一项不能自动接任务。
![Screenshot 2021-08-16 134407](https://user-images.githubusercontent.com/34137026/130322695-8c299a9f-e2d3-45db-8f48-7c04d61ca88d.png)
问题2：一些低等级任务需要“采摘”（需要点击黄色按钮）的无法继续。

**Comment by cwsam66** [comment]
问题1：每次都会这样？
运行脚本时建议把公会，队伍弹幕关掉
![图片](https://user-images.githubusercontent.com/46625727/130363738-ed339ac6-4db0-4cb3-8b13-19fed1941b30.png)

问题2：最新版本增加了只侦测“采”字的动作按钮

**Comment by shermanheng4862** [comment]
> 问题1：每次都会这样？

对，从第一个版本就这样。

https://user-images.githubusercontent.com/34137026/130399142-10904a5d-120a-4c72-b7dc-d86cd2e953aa.mp4

视频演示接任务过程和需要隐藏主线任务方可执行“点击任务框”。
只有当主线任务详情出现四行才需要隐藏主线任务。

[Screenshot_20210823-142650.zip](https://github.com/cwsam66/mobileanjian/files/7029589/Screenshot_20210823-142650.zip)
