### ISSUE TITLE
商会任务-无法自动接任务

### ISSUE THREAD

**Issue by shermanheng4862** [cwsam66/mobileanjian#2]
使用版本：激情ROX-辅助_20210821.apk
功能设置：商会任务，自动接任务，装备任务
问题：卡在对话界面，无法自动接任务。
![Screenshot 2021-08-21 211615](https://user-images.githubusercontent.com/34137026/130323018-9ba31794-fdda-4921-959d-6357d9587fd3.png)

**Comment by cwsam66** [comment]
Refer issue #3
