### ISSUE TITLE
商会任务-

### ISSUE THREAD

**Issue by shermanheng4862** [cwsam66/mobileanjian#3]
使用版本：激情ROX-辅助_20210821.apk
功能设置：商会任务，装备任务
问题：手动接任务后侦测不到目前在进行着什么动作。
![Screenshot 2021-08-21 212706](https://user-images.githubusercontent.com/34137026/130323392-8152cda1-9482-49ee-86d2-f2ee28511348.png)

**Comment by cwsam66** [comment]
可以截图看看你的游戏画面设置？

**Comment by shermanheng4862** [comment]
![Screenshot 2021-08-21 224037](https://user-images.githubusercontent.com/34137026/130325376-36ed3a03-0e16-46eb-b1e6-5b5bd1652b30.png)
![Screenshot 2021-08-21 224123](https://user-images.githubusercontent.com/34137026/130325418-ebba9bb2-4a34-4050-98e2-1403838b0296.png)

**Comment by cwsam66** [comment]
DPI for emulator? is 240?
latest apk updated to do less pixel check when in conversation with commercial NPC screen,
can help check if it still stuck

**Comment by shermanheng4862** [comment]
> DPI for emulator? is 240?

Yes, emulator is setup according to guide.

https://user-images.githubusercontent.com/34137026/130393219-ba7af759-dd30-4c3c-bef3-09d7fc7dbb0c.mp4

i interfere at 0:24, 0:55 and 1:37, the rest is script.

**Comment by cwsam66** [comment]
May need ur help on taking the screenshot at the conversation screen and commercial mission screen using the emulator screenshot button
![图片](https://user-images.githubusercontent.com/46625727/130398552-bc0357d0-15a6-4cdc-882f-f4068663749a.png)

then zip it and send here

**Comment by shermanheng4862** [comment]
[Screenshot_20210823-141730.zip](https://github.com/cwsam66/mobileanjian/files/7029562/Screenshot_20210823-141730.zip)
[Screenshot_20210823-160852.zip](https://github.com/cwsam66/mobileanjian/files/7030281/Screenshot_20210823-160852.zip)

**Comment by cwsam66** [comment]
可以试试最新版本看看这些问题还会不会发生

https://github.com/cwsam66/mobileanjian/blob/main/rox/%E6%BF%80%E6%83%85ROX-%E8%BE%85%E5%8A%A9-20210825.apk
