### ISSUE TITLE
园丁师傅 - 不能自动点击“园艺”动作按钮。

### ISSUE THREAD

**Issue by shermanheng4862** [cwsam66/mobileanjian#6]
使用版本：激情ROX-辅助-20210907.apk
功能设置：园丁师傅
问题：不能自动点击“园艺”动作按钮。

[Screenshot_20210908-151514.zip](https://github.com/cwsam66/mobileanjian/files/7126732/Screenshot_20210908-151514.zip)

**Comment by cwsam66** [comment]
https://github.com/cwsam66/mobileanjian/blob/main/rox/%E6%BF%80%E6%83%85ROX-%E8%BE%85%E5%8A%A9-20210910.apk

解决不能自动点击“园艺”动作按钮
